import {env} from 'cloudflare:workers';
const db=()=>{if(!env.DB)throw Error('Database unavailable');return env.DB};
const s=(v:unknown,max=150)=>typeof v==='string'?v.trim().slice(0,max):'';
const n=(v:unknown)=>typeof v==='number'&&Number.isFinite(v)?v:NaN;
const bad=(error:string,status=400)=>Response.json({error},{status});
const sizes:Record<string,number>={Regular:0,Large:15000,Party:30000},crusts:Record<string,number>={Classic:0,Thin:0,'Stuffed cheese':12000},toppings:Record<string,number>={'Extra cheese':6000,Pepperoni:7000,Mushrooms:4000,Jalapeños:4000},zones:Record<string,number>={'Manila':6900,'Makati':8900,'Pasig':9900};
async function detail(id:string){const d=db(),order=await d.prepare('SELECT * FROM orders WHERE id=?').bind(id).first(),[lines,history]=await d.batch([d.prepare('SELECT * FROM items WHERE order_id=? ORDER BY rowid').bind(id),d.prepare('SELECT * FROM events WHERE order_id=? ORDER BY created_at,rowid').bind(id)]);return {order,items:lines.results,events:history.results}}
function fail(e:unknown){console.error('Pizza API',e);return bad(e instanceof Error&&/FOREIGN KEY|UNIQUE/.test(e.message)?'The order could not be saved because availability changed. Please refresh or look up your order.':'Unable to complete the request. Please retry.',e instanceof Error&&/FOREIGN KEY|UNIQUE/.test(e.message)?409:500)}
export async function GET(request:Request){try{const d=db(),q=new URL(request.url).searchParams;if(q.get('mode')==='track'){const reference=s(q.get('reference'),30).toUpperCase(),email=s(q.get('email'),120).toLowerCase();const order=await d.prepare('SELECT id FROM orders WHERE reference=? AND email=?').bind(reference,email).first<{id:string}>();return order?Response.json(await detail(order.id)):bad('No order matches this reference and contact email.',404)}if(q.get('mode')==='staff'){const rows=await d.prepare('SELECT o.*,(SELECT SUM(quantity) FROM items i WHERE i.order_id=o.id) AS quantity FROM orders o ORDER BY created_at DESC LIMIT 500').all();return Response.json({orders:rows.results})}if(q.get('mode')==='detail'){const id=s(q.get('id'),40),r=await detail(id);return r.order?Response.json(r):bad('Order not found.',404)}const products=await d.prepare('SELECT * FROM products ORDER BY category,rowid').all();return Response.json({products:products.results,sizes,crusts,toppings,zones})}catch(e){return fail(e)}}
export async function POST(request:Request){let b:Record<string,unknown>;try{b=await request.json() as Record<string,unknown>}catch{return bad('Invalid JSON.')}try{const d=db(),now=new Date().toISOString(),id=s(b.id,40);
if(b.action==='seed'){if(await d.prepare('SELECT id FROM products LIMIT 1').first())return bad('The menu is already initialized.',409);const menu=[['Margherita','Rich tomato sauce, mozzarella and fresh basil.','Pizza',32900],['Pepperoni Classic','Mozzarella, tomato sauce and generous pepperoni.','Pizza',39900],['Four Cheese','Mozzarella, cheddar, parmesan and blue cheese.','Pizza',42900],['Garden Veggie','Bell peppers, mushrooms, onions and olives.','Pizza',36900],['BBQ Chicken','Smoky barbecue chicken, red onions and mozzarella.','Pizza',44900],['Meat Lovers','Pepperoni, ham, beef and Italian-style sausage.','Pizza',47900],['Garlic Bread','Oven-baked bread with garlic butter. Contains wheat and milk.','Sides',9900],['Chicken Wings','Six wings with smoky barbecue sauce.','Sides',24900],['Cola 330 ml','Chilled canned cola.','Drinks',5900],['Lemon Iced Tea','Refreshing bottled lemon tea.','Drinks',6900]];await d.batch(menu.map(p=>d.prepare('INSERT INTO products VALUES(?,?,?,?,?,1)').bind(crypto.randomUUID(),...p)));return Response.json({message:'Sample menu loaded.'})}
if(b.action==='product'){const name=s(b.name,80),description=s(b.description,250),category=s(b.category,20),price=n(b.priceCents);if(!name||!description||!['Pizza','Sides','Drinks'].includes(category)||!Number.isInteger(price)||price<100||price>1e7)return bad('Enter product name, description, category and a valid price.');if(id){const r=await d.prepare('UPDATE products SET name=?,description=?,category=?,price_cents=? WHERE id=?').bind(name,description,category,price,id).run();if(!r.meta.changes)return bad('Product not found.',404)}else await d.prepare('INSERT INTO products VALUES(?,?,?,?,?,1)').bind(crypto.randomUUID(),name,description,category,price).run();return Response.json({message:'Menu item saved.'})}
if(b.action==='availability'){const available=n(b.available);if(![0,1].includes(available))return bad('Invalid availability.');await d.prepare('UPDATE products SET available=? WHERE id=?').bind(available,id).run();return Response.json({message:'Availability updated.'})}
if(b.action==='order'){const name=s(b.customer,100),email=s(b.email,120).toLowerCase(),phone=s(b.phone,30),address=s(b.address,300),zone=s(b.zone,30),notes=s(b.notes,300),requestKey=s(b.requestKey,50),raw=b.items;if(!name||!/^\S+@\S+\.\S+$/.test(email)||phone.length<7||address.length<10||!Object.hasOwn(zones,zone)||!/^\w[\w-]{15,49}$/.test(requestKey)||!Array.isArray(raw)||raw.length<1||raw.length>20)return bad('Complete delivery details and add 1–20 cart lines.');const existing=await d.prepare('SELECT id,email FROM orders WHERE request_key=?').bind(requestKey).first<{id:string;email:string}>();if(existing)return existing.email===email?Response.json(await detail(existing.id)):bad('Request key unavailable.',409);
const lines=[];for(const value of raw){const row=value as Record<string,unknown>,productId=s(row?.productId,40),quantity=n(row?.quantity),size=s(row?.size,30),crust=s(row?.crust,30),extra=row?.extras;if(!Number.isInteger(quantity)||quantity<1||quantity>10||!Array.isArray(extra)||extra.length>4)return bad('Each cart line needs 1–10 items and valid customizations.');const product=await d.prepare('SELECT * FROM products WHERE id=? AND available=1').bind(productId).first<{id:string;name:string;category:string;price_cents:number}>();if(!product)return bad('A menu item is no longer available. Refresh your cart.',409);const extras=extra.map(x=>s(x,30));if(new Set(extras).size!==extras.length)return bad('Toppings must be distinct.');let unit=product.price_cents;if(product.category==='Pizza'){if(!Object.hasOwn(sizes,size)||!Object.hasOwn(crusts,crust)||extras.some(x=>!Object.hasOwn(toppings,x)))return bad('Choose a valid size, crust and toppings.');unit+=sizes[size]+crusts[crust]+extras.reduce((v,x)=>v+toppings[x],0)}else if(size||crust||extras.length)return bad('Sides and drinks do not accept pizza customizations.');lines.push({id:crypto.randomUUID(),productId,name:product.name,size,crust,extras,quantity,unit})}
const subtotal=lines.reduce((v,l)=>v+l.unit*l.quantity,0);if(subtotal<29900)return bad('Delivery requires a minimum item subtotal of ₱299.');if(subtotal>2000000)return bad('Orders are limited to ₱20,000.');const oid=crypto.randomUUID(),reference='FS-'+crypto.randomUUID().slice(0,8).toUpperCase(),fee=zones[zone],ids=[...new Set(lines.map(l=>l.productId))],marks=ids.map(()=>'?').join(',');const stmts=[d.prepare(`INSERT INTO orders(id,reference,request_key,customer,email,phone,address,zone,notes,subtotal_cents,delivery_cents,total_cents,status,payment_status,rider,created_at) SELECT ?,?,?,?,?,?,?,?,?,?,?,?,'Placed','Unpaid','',? WHERE (SELECT COUNT(*) FROM products WHERE id IN (${marks}) AND available=1)=?`).bind(oid,reference,requestKey,name,email,phone,address,zone,notes,subtotal,fee,subtotal+fee,now,...ids,ids.length),...lines.map(l=>d.prepare('INSERT INTO items VALUES(?,?,?,?,?,?,?,?,?)').bind(l.id,oid,l.productId,l.name,l.size,l.crust,JSON.stringify(l.extras),l.quantity,l.unit)),d.prepare("INSERT INTO events VALUES(?,?,'Placed',?)").bind(crypto.randomUUID(),oid,now)];await d.batch(stmts);return Response.json(await detail(oid),{status:201})}
if(b.action==='cancel'){const reference=s(b.reference,30).toUpperCase(),email=s(b.email,120).toLowerCase(),order=await d.prepare('SELECT id FROM orders WHERE reference=? AND email=?').bind(reference,email).first<{id:string}>();if(!order)return bad('Order not found.',404);const r=await d.batch([d.prepare("UPDATE orders SET status='Cancelled' WHERE id=? AND status='Placed'").bind(order.id),d.prepare("INSERT INTO events(id,order_id,status,created_at) SELECT ?,?,'Cancelled',? WHERE EXISTS(SELECT 1 FROM orders WHERE id=? AND status='Cancelled') AND NOT EXISTS(SELECT 1 FROM events WHERE order_id=? AND status='Cancelled')").bind(crypto.randomUUID(),order.id,now,order.id,order.id)]);return r[0].meta.changes?Response.json({message:'Order cancelled.'}):bad('Only orders still awaiting acceptance can be cancelled.',409)}
if(b.action==='status'){const from=s(b.from,30),to=s(b.status,30),rider=s(b.rider,80),transitions:Record<string,string[]>={Placed:['Accepted','Cancelled'],Accepted:['Preparing','Cancelled'],Preparing:['Out for delivery'], 'Out for delivery':['Delivered']};if(!transitions[from]?.includes(to)||to==='Out for delivery'&&!rider)return bad('Choose the next valid status and assign a rider before dispatch.');const r=await d.batch([d.prepare('UPDATE orders SET status=?,rider=CASE WHEN ?=? THEN ? ELSE rider END WHERE id=? AND status=?').bind(to,to,'Out for delivery',rider,id,from),d.prepare('INSERT INTO events(id,order_id,status,created_at) SELECT ?,?,?,? WHERE EXISTS(SELECT 1 FROM orders WHERE id=? AND status=?) AND NOT EXISTS(SELECT 1 FROM events WHERE order_id=? AND status=?)').bind(crypto.randomUUID(),id,to,now,id,to,id,to)]);return r[0].meta.changes?Response.json({message:'Order status updated.'}):bad('Order status changed. Refresh and try again.',409)}
if(b.action==='payment'){const r=await d.prepare("UPDATE orders SET payment_status='Paid' WHERE id=? AND status='Delivered' AND payment_status='Unpaid'").bind(id).run();return r.meta.changes?Response.json({message:'Cash payment recorded.'}):bad('Cash payment can be recorded once after delivery.',409)}
return bad('Unknown action.');}catch(e){return fail(e)}}
